language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: SECRET_KEY_BASE
  app: pawty-trainer-api
  run: rails db:migrate
  on: 
    branch:
      main
